#!/bin/bash -e

if [[ "$SHELL" =~ bash ]]; then
  files="env_vars.sh post-commit post-merge pre-commit"

  if [[ -n $@ ]]; then
    for git_root in $@; do
      if test -d "$git_root/.git/hooks"; then
        cp -a $files "$git_root/.git/hooks/"
        echo "Git Claws installed for $git_root"
      else
        echo "No git repo found at $git_root, skipping."
      fi
    done
  else
    echo 'Usage: ./install_git_claws "/your/project/path" [ "/additional/project/path" ... ]'
  fi
else
  echo "ERROR: Please run using bash, not $SHELL"
fi
