#!/bin/bash -e

git_root=`git rev-parse --show-toplevel`
source "$git_root/.git/hooks/env_vars.sh"
if [[ -e "$git_root/Gemfile" ]]; then
  echo "Bundling gems..."
  cd "$git_root"
  bundle install --system
  cd -
fi

if [[ -e "$git_root/setup.py" ]]; then
  echo "Running 'python setup.py install'..."
  cd "$git_root"
  python setup.py install
  cd -
fi

if [[ -e "$git_root/package.json" ]]; then
  echo "Running 'npm install'..."
  cd "$git_root"
  npm install
  cd -
fi
